version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    container_name: ss-postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - backend/.env
    ports:
      - "5445:5432"
    restart: always

  redis:
    image: redis
    container_name: ss-redis
    restart: always
    ports:
      - "6378:6378"

  telebot:
    build: ./telebot
    container_name: ss-telebot
    ports:
      - "8009:8009"
    restart: on-failure
    depends_on:
      - redis

  backend:
    build: ./backend
    container_name: ss-backend
    volumes:
      - .:/src/app/
    ports:
      - "8008:8008"
    env_file:
      - backend/.env
    restart: on-failure
    depends_on:
      - db

volumes:
  db:
    driver: local