version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    container_name: ss-postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - backend/.env
    ports:
      - "5445:5432"
    restart: always

  redis:
    image: redis:7.0.2-alpine
    container_name: ss-redis
    restart: on-failure
    command: --port 6378
    ports:
      - "6378:6378"
    expose:
      - "6378"

  mongodb:
    image: mongo
    container_name: ss-mongodb
    volumes:
      - ./mongodb_data:/var/lib/mongodb/data
    env_file:
      - telebot/.env
    ports:
      - "27017:27017"
    expose:
      - "27017"
    command: mongod
    restart: on-failure

  celery:
    build: ./telebot
    container_name: ss-celery
    command: celery -A tasks worker --loglevel=INFO
    volumes:
      - ./celery_data:/var/lib/celery/data
    env_file:
      - telebot/.env
    restart: on-failure
    depends_on:
      - redis

  telebot:
    build: ./telebot
    container_name: ss-telebot
    ports:
      - "8009:8009"
    restart: on-failure
    depends_on:
      - redis
      - mongodb
      - celery

  backend:
    build: ./backend
    container_name: ss-backend
    volumes:
      - .:/src/app/
    ports:
      - "8008:8008"
    env_file:
      - backend/.env
    restart: on-failure
    depends_on:
      - db

volumes:
  mongodb_data:
  postgres_data:
  db:
    driver: local