version: "3.8"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ssb-rabbitmq
    env_file:
      - .env
#    restart: always
    ports:
      # AMQP protocol port
      - "5671:5672"
      # HTTP management UI
      - "15671:15672"

  db:
    image: postgres:14.1-alpine
    container_name: ssb-postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5445:5432"
    restart: always

  redis:
    image: redis:7.0.2-alpine
    container_name: ssb-redis
#    restart: on-failure
    command: --port 6378
    ports:
      - "6378:6378"
    expose:
      - "6378"

  backend:
    build:
      context: ./
      dockerfile: ./compose/local/Dockerfile
    command: /start
    container_name: ssb-backend
    volumes:
      - .:/src/app/
    ports:
      - "8008:8008"
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - redis
      - db
      - rabbitmq

  celery:
    build:
      context: ./
      dockerfile: ./compose/local/Dockerfile
    container_name: ssb-celery
    command: /start-celeryworker
    volumes:
      - .:/src/app/
    environment:
      - CELERY_BROKER_URL=redis://redis:6378/0
      - CELERY_RESULT_BACKEND=redis://redis:6378/0
    depends_on:
      - redis
      - backend

  celery-beat:
    build:
      context: ./
      dockerfile: ./compose/local/Dockerfile
    container_name: ssb-celery-beat
    command: /start-celerybeat
    volumes:
      - .:/src/app
#    env_file:
#      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6378/0
      - CELERY_RESULT_BACKEND=redis://redis:6378/0
    depends_on:
      - redis
      - backend
      - rabbitmq

  flower:
    build:
      context: ./
      dockerfile: ./compose/local/Dockerfile
    container_name: ssb-flower
    image: mher/flower
    command: /start-flower
    env_file: .env
    volumes:
      - .:/src/app
    expose:
      - 5555
    ports:
      - "5555:5555"

volumes:
  postgres_data:
  rabbitmq_data:
