version: "3.8"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: t-rabbitmq
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq/data
    env_file:
      - .env
    restart: always
    ports:
      # AMQP protocol port
      - "5673:5673"
      # HTTP management UI
      - "15673:15672"

  redis:
    image: redis:7.0.2-alpine
    container_name: t-redis
    restart: on-failure
    command: --port 6377
    ports:
      - "6377:6377"
    expose:
      - "6377"

  mongodb:
    image: mongo
    container_name: t-mongodb
    volumes:
      - ./mongodb_data:/var/lib/mongodb/data
    env_file:
      - .env
    ports:
      - "27017:27017"
    expose:
      - "27017"
    command: mongod
    restart: on-failure

  celery:
    build: ./
    container_name: t-celery
    command: celery worker --loglevel=info
    volumes:
      - ./celery_data/worker/:/var/lib/celery/worked
#    env_file:
#      - .env
    environment:
      - CELERY_BROKER_URL=redis://redis:6377/0
      - CELERY_RESULT_BACKEND=redis://redis:6377/0
    restart: on-failure
    depends_on:
      - redis
      - telebot

  celery-beat:
    build: ./
    container_name: t-celery-beat
    command: celery beat --loglevel=info
    volumes:
      - ./celery_data/beat/:/var/lib/celery/beat
    env_file:
      - .env
#    environment:
#      - DEBUG=1
#      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
#      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
    depends_on:
      - redis
      - telebot

  telebot:
    build: ./
    container_name: t-telebot
    command: python3 main.py
    ports:
      - "8009:8009"
    restart: on-failure
    depends_on:
      - redis
      - mongodb
      - rabbitmq

  flower:
    build: ./
    image: mher/flower
    environment:
      - CELERY_BROKER_URL=redis://redis:6377/0
      - FLOWER_PORT=8888
#    env_file:
#      - .env
    ports:
      - "8888:8888"
    depends_on:
      - redis

volumes:
  celery_data:
  rabbitmq_data:
  mongodb_data:
  db:
    driver: local