"""gives_to-fro

Revision ID: 2898e4b3b0f7
Revises: b6dbf2644958
Create Date: 2022-07-01 17:05:30.307927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2898e4b3b0f7'
down_revision = 'b6dbf2644958'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('santa_code', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('gives_to_id', sa.Integer(), nullable=True))
    op.drop_constraint('player_santa_id_fkey', 'player', type_='foreignkey')
    op.create_foreign_key(None, 'player', 'secretsanta', ['santa_code'], ['code'])
    op.create_foreign_key(None, 'player', 'player', ['gives_to_id'], ['id'])
    op.drop_column('player', 'santa_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('santa_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.create_foreign_key('player_santa_id_fkey', 'player', 'secretsanta', ['santa_id'], ['id'])
    op.drop_column('player', 'gives_to_id')
    op.drop_column('player', 'santa_code')
    # ### end Alembic commands ###
