"""gives_to_id-nullable

Revision ID: 4ae2ea05b6e6
Revises: 2898e4b3b0f7
Create Date: 2022-07-01 17:07:56.831018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ae2ea05b6e6'
down_revision = '2898e4b3b0f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
