"""currencies

Revision ID: b6dbf2644958
Revises: 2481f039fa4c
Create Date: 2022-07-01 15:46:11.641918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision = 'b6dbf2644958'
down_revision = '2481f039fa4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    enum = ENUM('BYN', 'USD', 'EUR', 'RUB', name='currencytype', create_type=False)
    enum.create(op.get_bind(), checkfirst=False)
    op.add_column('secretsanta', sa.Column('currency_iso3', enum, nullable=True))
    op.add_column('secretsanta', sa.Column('expected_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('secretsanta', 'currency_iso3')
    ENUM(name='currencytype').drop(op.get_bind(), checkfirst=False)
    op.drop_column('secretsanta', 'expected_amount')
    # ### end Alembic commands ###
